name: Go CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build user-service
        working-directory: services/user-service
        run: go build -v .

      - name: Run tests
        working-directory: services/user-service
        run: go test ./...

      - name: Build Docker image
        run: docker build -t user-service:latest services/user-service

      # Add push to DockerHub/AWS ECR if needed