package bootstrap

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/Gursevak56/food-delivery-platform/services/rider-service/internal/app"
	"github.com/Gursevak56/food-delivery-platform/services/rider-service/internal/domain"
	"github.com/Gursevak56/food-delivery-platform/services/rider-service/internal/middleware"
	"github.com/Gursevak56/food-delivery-platform/services/rider-service/pkg/response"
)

func NewRouter(container *app.Container) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	router := gin.New()
	router.Use(middleware.RequestID(), middleware.Recovery(container.Logger), middleware.AccessLog(container.Logger))

	router.GET("/health/live", func(c *gin.Context) {
		response.Success(c, http.StatusOK, "service is live", gin.H{"service": container.Config.App.Name, "mode": container.Config.App.Environment}, nil)
	})
	router.GET("/health/ready", container.HealthHandler.Ready)
	router.GET("/docs/openapi.yaml", container.DocsHandler.OpenAPI)

	v1 := router.Group("/v1")
	authGroup := v1.Group("/auth")
	authGroup.Use(middleware.RateLimit("auth", 20, 1))
	authGroup.POST("/rider/login", container.AuthHandler.Login)
	authGroup.POST("/rider/otp/send", container.AuthHandler.SendOTP)
	authGroup.POST("/rider/otp/verify", container.AuthHandler.VerifyOTP)
	authGroup.POST("/refresh-token", container.AuthHandler.RefreshToken)
	authGroup.POST("/forgot-password", container.AuthHandler.ForgotPassword)
	authGroup.POST("/reset-password", container.AuthHandler.ResetPassword)
	authProtected := authGroup.Group("/")
	authProtected.Use(middleware.Authenticate(container.AuthManager))
	authProtected.POST("/logout", container.AuthHandler.Logout)
	authProtected.POST("/logout-all", container.AuthHandler.LogoutAll)
	authProtected.GET("/me", container.AuthHandler.Me)

	protected := v1.Group("/")
	protected.Use(middleware.Authenticate(container.AuthManager))

	riders := protected.Group("/riders/me")
	riders.Use(middleware.RequireAnyRole(domain.RoleRider))
	riders.GET("", container.RiderHandler.GetProfile)
	riders.PUT("", container.RiderHandler.UpdateProfile)
	riders.PUT("/photo", container.RiderHandler.UpdatePhoto)
	riders.PUT("/vehicle", container.RiderHandler.UpdateVehicle)
	riders.PUT("/documents", container.RiderHandler.UpdateDocuments)
	riders.GET("/documents", container.RiderHandler.GetDocuments)
	riders.PUT("/bank-account", container.RiderHandler.UpsertBankAccount)
	riders.GET("/status", container.RiderHandler.GetStatus)
	riders.POST("/go-online", container.ShiftHandler.GoOnline)
	riders.POST("/go-offline", container.ShiftHandler.GoOffline)
	riders.POST("/break/start", container.ShiftHandler.StartBreak)
	riders.POST("/break/end", container.ShiftHandler.EndBreak)
	riders.POST("/shift/start", container.ShiftHandler.StartShift)
	riders.POST("/shift/end", container.ShiftHandler.EndShift)
	riders.GET("/shift/today", container.ShiftHandler.GetTodayShift)
	riders.GET("/shift/history", container.ShiftHandler.GetShiftHistory)
	riders.GET("/order-requests", container.DispatchHandler.ListOrderRequests)
	riders.GET("/order-requests/:id", container.DispatchHandler.GetOrderRequest)
	riders.POST("/order-requests/:id/accept", container.DispatchHandler.AcceptOrderRequest)
	riders.POST("/order-requests/:id/reject", container.DispatchHandler.RejectOrderRequest)
	riders.GET("/active-order", container.DispatchHandler.GetActiveOrder)
	riders.GET("/orders/assigned", container.DispatchHandler.ListAssignedOrders)
	riders.GET("/orders/history", container.DispatchHandler.ListOrderHistory)
	riders.GET("/orders/:orderId", container.DispatchHandler.GetOrder)
	riders.POST("/orders/:orderId/arrived-at-restaurant", container.DispatchHandler.MarkArrivedRestaurant)
	riders.POST("/orders/:orderId/picked-up", container.DispatchHandler.MarkPickedUp)
	riders.POST("/orders/:orderId/start-delivery", container.DispatchHandler.MarkOnTheWay)
	riders.POST("/orders/:orderId/arrived-at-customer", container.DispatchHandler.MarkArrivedCustomer)
	riders.POST("/orders/:orderId/deliver", container.DispatchHandler.MarkDelivered)
	riders.POST("/orders/:orderId/failed", container.DispatchHandler.MarkFailed)
	riders.POST("/orders/:orderId/cancel-request", container.DispatchHandler.RequestCancel)
	riders.GET("/orders/:orderId/timeline", container.DispatchHandler.GetTimeline)
	riders.POST("/orders/:orderId/verify-pickup-otp", container.DispatchHandler.VerifyPickupOTP)
	riders.POST("/orders/:orderId/verify-delivery-otp", container.DispatchHandler.VerifyDeliveryOTP)
	riders.POST("/location/update", container.LocationHandler.UpdateLocation)
	riders.POST("/location/bulk-update", container.LocationHandler.BulkUpdateLocation)
	riders.GET("/location/latest", container.LocationHandler.GetLatestLocation)
	riders.GET("/routes/:orderId", container.LocationHandler.GetRouteHistory)
	riders.GET("/earnings/today", container.FinanceHandler.GetTodayEarnings)
	riders.GET("/earnings/weekly", container.FinanceHandler.GetWeeklyEarnings)
	riders.GET("/earnings/monthly", container.FinanceHandler.GetMonthlyEarnings)
	riders.GET("/earnings/summary", container.FinanceHandler.GetEarningsSummary)
	riders.GET("/earnings/history", container.FinanceHandler.GetEarningsHistory)
	riders.GET("/incentives", container.FinanceHandler.GetIncentives)
	riders.GET("/bonus-history", container.FinanceHandler.GetBonusHistory)
	riders.GET("/wallet", container.FinanceHandler.GetWallet)
	riders.GET("/wallet/transactions", container.FinanceHandler.GetWalletTransactions)
	riders.GET("/payouts", container.FinanceHandler.GetPayouts)
	riders.GET("/payouts/:id", container.FinanceHandler.GetPayout)
	riders.POST("/payouts/request", container.FinanceHandler.RequestPayout)
	riders.GET("/bank-account", container.FinanceHandler.GetBankAccount)
	riders.GET("/ratings/summary", container.FeedbackHandler.GetRatingsSummary)
	riders.GET("/reviews", container.FeedbackHandler.GetReviews)
	riders.GET("/performance-score", container.FeedbackHandler.GetPerformanceScore)
	riders.GET("/notifications", container.NotificationHandler.ListNotifications)
	riders.PUT("/notifications/:id/read", container.NotificationHandler.MarkRead)
	riders.PUT("/notifications/read-all", container.NotificationHandler.MarkAllRead)
	riders.POST("/device-token", container.NotificationHandler.RegisterDeviceToken)
	riders.DELETE("/device-token", container.NotificationHandler.DeleteDeviceToken)
	riders.POST("/support-tickets", container.SupportHandler.CreateTicket)
	riders.GET("/support-tickets", container.SupportHandler.ListTickets)
	riders.GET("/support-tickets/:id", container.SupportHandler.GetTicket)
	riders.POST("/support-tickets/:id/reply", container.SupportHandler.ReplyTicket)

	protected.GET("/orders/:orderId/tracking", container.LocationHandler.GetOrderTracking)
	protected.POST("/orders/:orderId/resend-delivery-otp", middleware.RequireAnyRole(domain.RoleDispatcherManager, domain.RoleRestaurantAdmin, domain.RoleRestaurantOwner, domain.RoleSuperAdmin), container.DispatchHandler.ResendDeliveryOTP)
	protected.POST("/orders/:orderId/resend-pickup-otp", middleware.RequireAnyRole(domain.RoleDispatcherManager, domain.RoleRestaurantAdmin, domain.RoleRestaurantOwner, domain.RoleSuperAdmin), container.DispatchHandler.ResendPickupOTP)

	admin := v1.Group("/admin")
	admin.Use(middleware.Authenticate(container.AuthManager), middleware.RequireAnyRole(domain.RoleSuperAdmin, domain.RoleRestaurantOwner, domain.RoleRestaurantAdmin, domain.RoleDispatcherManager))
	admin.GET("/riders", container.AdminHandler.ListRiders)
	admin.GET("/riders/:id", container.AdminHandler.GetRider)
	admin.POST("/riders", container.AdminHandler.CreateRider)
	admin.PUT("/riders/:id", container.AdminHandler.UpdateRider)
	admin.PUT("/riders/:id/status", container.AdminHandler.UpdateRiderStatus)
	admin.GET("/orders/unassigned", container.AdminHandler.ListUnassignedOrders)
	admin.POST("/orders/:orderId/assign-rider", container.AdminHandler.AssignRider)
	admin.POST("/orders/:orderId/reassign-rider", container.AdminHandler.ReassignRider)
	admin.GET("/orders/live", container.AdminHandler.ListLiveOrders)
	admin.GET("/riders/live-status", container.AdminHandler.ListLiveRiderStatus)
	admin.GET("/analytics/riders", container.AdminHandler.GetRiderAnalytics)
	admin.GET("/config", container.AdminHandler.GetSystemConfig)
	admin.PUT("/config", container.AdminHandler.UpdateSystemConfig)
	admin.GET("/payouts", container.AdminHandler.ListPayoutRequests)
	admin.POST("/payouts/:id/approve", container.AdminHandler.ApprovePayout)
	admin.POST("/payouts/:id/reject", container.AdminHandler.RejectPayout)

	return router
}
